In [57]:
import numpy as np
from sklearn.linear_model import LogisticRegression, LinearRegression

In [58]:
#init test data
timestamps = np.arange(0,30000, 10) #100 stamps per second, 30 seconds
timestamps = timestamps.reshape((-1,1))
motor_values = np.zeros((timestamps.shape[0], 2))
print(motor_values, motor_values.shape)

#generate test data
for i in range(motor_values.shape[0]):
    motor_values[i] = [3* i / 100, 3* i / 100]
    
for i in range(500, 1000, 1): #from 5s to 10s turn slowly right
    motor_values[i] = [5, 0]
    
for i in range(1500, 2000, 1): #from 15s to 20s turn slowly left on spot
    motor_values[i] = [-5, 5]


print(motor_values, motor_values.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]] (3000, 2)
[[0.000e+00 0.000e+00]
 [3.000e-02 3.000e-02]
 [6.000e-02 6.000e-02]
 ...
 [8.991e+01 8.991e+01]
 [8.994e+01 8.994e+01]
 [8.997e+01 8.997e+01]] (3000, 2)


In [59]:
#add noice
motor_values = motor_values + np.random.normal(scale = 0.1, size=(motor_values.shape))
print (motor_values)

[[ 3.28811374e-02 -1.77680443e-02]
 [-3.42789810e-02  9.21621829e-02]
 [ 1.59784293e-01  2.21492042e-01]
 ...
 [ 8.99064981e+01  8.99238709e+01]
 [ 9.01153018e+01  8.97994912e+01]
 [ 9.00075979e+01  8.99644065e+01]]


In [61]:
model = LogisticRegression()
model = LinearRegression()
model.fit(timestamps, motor_values)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [62]:
model.coef_

array([[0.002944  ],
       [0.00308305]])

In [63]:
model.intercept_

array([-11.65378973, -12.90871691])

In [64]:
model.predict((12345))

array([[24.68985057, 25.15159205]])

In [65]:
for i in range(0, timestamps.shape[0], 10):
    print("time ", timestamps[i], "ms, prediction ", model.predict((timestamps[i],)), " real ", motor_values[i])

time  [0] ms, prediction  [[-11.65378973 -12.90871691]]  real  [ 0.03288114 -0.01776804]
time  [100] ms, prediction  [[-11.35939005 -12.60041145]]  real  [0.46435137 0.18301457]
time  [200] ms, prediction  [[-11.06499038 -12.29210599]]  real  [0.43218288 0.61913643]
time  [300] ms, prediction  [[-10.7705907  -11.98380053]]  real  [0.98431265 0.81704948]
time  [400] ms, prediction  [[-10.47619102 -11.67549507]]  real  [1.2525728  1.11745746]
time  [500] ms, prediction  [[-10.18179134 -11.36718961]]  real  [1.55250054 1.50963542]
time  [600] ms, prediction  [[ -9.88739166 -11.05888415]]  real  [1.77814481 1.72339573]
time  [700] ms, prediction  [[ -9.59299198 -10.75057869]]  real  [2.14818449 2.09918612]
time  [800] ms, prediction  [[ -9.29859231 -10.44227323]]  real  [2.56456063 2.402783  ]
time  [900] ms, prediction  [[ -9.00419263 -10.13396777]]  real  [2.77257201 2.73406412]
time  [1000] ms, prediction  [[-8.70979295 -9.82566231]]  real  [3.15664622 2.95270995]
time  [1100] ms, predi

time  [22100] ms, prediction  [[53.4085392  55.22678961]]  real  [66.27538251 66.23030465]
time  [22200] ms, prediction  [[53.70293888 55.53509507]]  real  [66.62689085 66.71678813]
time  [22300] ms, prediction  [[53.99733855 55.84340053]]  real  [66.90761544 66.82939388]
time  [22400] ms, prediction  [[54.29173823 56.15170599]]  real  [67.23931919 67.16172615]
time  [22500] ms, prediction  [[54.58613791 56.46001145]]  real  [67.37423576 67.39974718]
time  [22600] ms, prediction  [[54.88053759 56.7683169 ]]  real  [67.74859616 67.74730251]
time  [22700] ms, prediction  [[55.17493727 57.07662236]]  real  [68.16437971 68.10875108]
time  [22800] ms, prediction  [[55.46933695 57.38492782]]  real  [68.19818893 68.37139825]
time  [22900] ms, prediction  [[55.76373663 57.69323328]]  real  [68.65801652 68.6616134 ]
time  [23000] ms, prediction  [[56.0581363  58.00153874]]  real  [69.08625613 68.80553196]
time  [23100] ms, prediction  [[56.35253598 58.3098442 ]]  real  [69.31013109 69.21165522]